/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graham.lynch.quiz.oop.project;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author graha
 */
public class PlayGame extends javax.swing.JFrame {
    FileIO myFileIO = new FileIO();
    String name;
    String question;
    int score, score1;
    
    ArrayList<Quiz> questions1 = new ArrayList<Quiz>();
    
    /**
     * Creates new form PlayGame
     * @param name
     */
    public PlayGame(String name) {
        initComponents();
        questions1 = myFileIO.readQuestionsFromFile();
        DisplayQuestion();
        this.name=name;
        System.out.print(name);
        score1 = 0;
        this.question=question;
         
    }
    
   

    
    public void DisplayQuestion(){
    Random random = new Random();
    int numberOfQuestions = questions1.size();
    for (int i = 0; i < 5; i++) {
    int randomNum1 = random.nextInt(numberOfQuestions);
    int randomNum2 = random.nextInt(numberOfQuestions);
    int randomNum3 = random.nextInt(numberOfQuestions);
    int randomNum4 = random.nextInt(numberOfQuestions);
    int randomNum5 = random.nextInt(numberOfQuestions);
    Quiz randomQuestion1 = questions1.get(randomNum1);
    Quiz randomQuestion2 = questions1.get(randomNum2);
    Quiz randomQuestion3 = questions1.get(randomNum3);
    Quiz randomQuestion4 = questions1.get(randomNum4);
    Quiz randomQuestion5 = questions1.get(randomNum5);
    question1.setText(randomQuestion1.getQuestion());
    question2.setText(randomQuestion2.getQuestion());
    question3.setText(randomQuestion3.getQuestion());
    question4.setText(randomQuestion4.getQuestion());
    question5.setText(randomQuestion5.getQuestion());
    }
        /*question2.setText(questions1.get(1).getQuestion());
        question3.setText(questions1.get(1).getQuestion());
        question4.setText(questions1.get(1).getQuestion());
        question5.setText(questions1.get(1).getQuestion());*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        answer1 = new javax.swing.JTextField();
        answer2 = new javax.swing.JTextField();
        answer3 = new javax.swing.JTextField();
        answer4 = new javax.swing.JTextField();
        answer5 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(20, 20));

        question2.setBackground(new java.awt.Color(51, 51, 255));

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit Name & Answers");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("What is your name?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(answer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(answer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButton)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        if ("Who is the president of the United States of America?".equals(question1.getText())&&"Donald Trump".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
      
        if("What is the second smallest county in Ireland?".equals(question1.getText())&&"Louth".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
       
        if("What is the County town of County Kerry?".equals(question1.getText())&&"Tralee".equals(answer1.getText())){
           JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
           score ++;
        }
       
        if("The Book of Kells was written in what language?".equals(question1.getText())&&"Latin".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
      
        if("In what year was the Battle of Clontarf?".equals(question1.getText())&&"1014".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
      
         if("What was the first country to win the World Cup twice?".equals(question1.getText())&&"Italy".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
       
        if("What does NCI stand for?".equals(question1.getText())&&"National College of Ireland".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
        
        if("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?".equals(question1.getText())&&"Thomas Jefferson".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
       
        if("What stadium to Arsenal Football club play in?".equals(question1.getText())&&"Emirates Stadium".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
       
         if("What is the capital of England?".equals(question1.getText())&&"London".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
            score ++;
        }
      
        if ("Who is the president of the United States of America?".equals(question2.getText())&&"Donald Trump".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
       
        if("What is the second smallest county in Ireland?".equals(question2.getText())&&"Louth".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
       
        if("What is the County town of County Kerry?".equals(question2.getText())&&"Tralee".equals(answer2.getText())){
           JOptionPane.showMessageDialog(null, "Answer 1 was Correct");
           score ++;
        }
      
        if("The Book of Kells was written in what language?".equals(question2.getText())&&"Latin".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
      
        if("In what year was the Battle of Clontarf?".equals(question2.getText())&&"1014".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
      
         if("What was the first country to win the World Cup twice?".equals(question2.getText())&&"Italy".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
       
        if("What does NCI stand for?".equals(question2.getText())&&"National College of Ireland".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
       
        if("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?".equals(question2.getText())&&"Thomas Jefferson".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
      
        if("What stadium to Arsenal Football club play in?".equals(question2.getText())&&"Emirates Stadium".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
      
         if("What is the capital of England?".equals(question2.getText())&&"London".equals(answer2.getText())){
            JOptionPane.showMessageDialog(null, "Answer 2 was Correct");
            score ++;
        }
       
              if ("Who is the president of the United States of America?".equals(question3.getText())&&"Donald Trump".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
      
        if("What is the second smallest county in Ireland?".equals(question3.getText())&&"Louth".equals(answer1.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
      
        if("What is the County town of County Kerry?".equals(question3.getText())&&"Tralee".equals(answer3.getText())){
           JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
           score ++;
        }
      
        if("The Book of Kells was written in what language?".equals(question3.getText())&&"Latin".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
       
        if("In what year was the Battle of Clontarf?".equals(question3.getText())&&"1014".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
      
         if("What was the first country to win the World Cup twice?".equals(question3.getText())&&"Italy".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
      
        if("What does NCI stand for?".equals(question3.getText())&&"National College of Ireland".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
     
        if("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?".equals(question3.getText())&&"Thomas Jefferson".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
     
        if("What stadium to Arsenal Football club play in?".equals(question3.getText())&&"Emirates Stadium".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
     
         if("What is the capital of England?".equals(question3.getText())&&"London".equals(answer3.getText())){
            JOptionPane.showMessageDialog(null, "Answer 3 was Correct");
            score ++;
        }
      
        if ("Who is the president of the United States of America?".equals(question4.getText())&&"Donald Trump".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
      
        if("What is the second smallest county in Ireland?".equals(question4.getText())&&"Louth".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
      
        if("What is the County town of County Kerry?".equals(question4.getText())&&"Tralee".equals(answer4.getText())){
           JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
           score ++;
        }
     
        if("The Book of Kells was written in what language?".equals(question4.getText())&&"Latin".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
     
        if("In what year was the Battle of Clontarf?".equals(question4.getText())&&"1014".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
   
         if("What was the first country to win the World Cup twice?".equals(question4.getText())&&"Italy".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
 
        if("What does NCI stand for?".equals(question4.getText())&&"National College of Ireland".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
   
        if("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?".equals(question4.getText())&&"Thomas Jefferson".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
    
        if("What stadium to Arsenal Football club play in?".equals(question4.getText())&&"Emirates Stadium".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
     
         if("What is the capital of England?".equals(question4.getText())&&"London".equals(answer4.getText())){
            JOptionPane.showMessageDialog(null, "Answer 4 was Correct");
            score ++;
        }
      
            if ("Who is the president of the United States of America?".equals(question5.getText())&&"Donald Trump".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
      
        if("What is the second smallest county in Ireland?".equals(question5.getText())&&"Louth".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
   
        if("What is the County town of County Kerry?".equals(question5.getText())&&"Tralee".equals(answer5.getText())){
           JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
           score ++;
        }
 
        if("The Book of Kells was written in what language?".equals(question5.getText())&&"Latin".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
    
        if("In what year was the Battle of Clontarf?".equals(question5.getText())&&"1014".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
      
         if("What was the first country to win the World Cup twice?".equals(question5.getText())&&"Italy".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
      
        if("What does NCI stand for?".equals(question5.getText())&&"National College of Ireland".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
     
        if("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?".equals(question5.getText())&&"Thomas Jefferson".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }

        if("What stadium to Arsenal Football club play in?".equals(question5.getText())&&"Emirates Stadium".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }

         if("What is the capital of England?".equals(question5.getText())&&"London".equals(answer5.getText())){
            JOptionPane.showMessageDialog(null, "Answer 5 was Correct");
            score ++;
        }
     
      name = nameField.getText();
         JOptionPane.showMessageDialog(null, name +" You scored" + score +" /5");
     
     score1=score;
     
     Quiz1 myQuiz = new Quiz1(name, score1);
     myQuiz.setName(name);
     myQuiz.setScore1(score1);
     
     File outFile;
     FileOutputStream fStream;
     ObjectOutputStream oStream;
     
     try{
         outFile = new File ("namesandscores.dat");
         fStream = new FileOutputStream (outFile);
         oStream = new ObjectOutputStream (fStream);
         
         oStream.writeObject(myQuiz);
         
         JOptionPane.showMessageDialog(null, "Player and Score Saved Successfuly");
     }
     catch(IOException e){
         JOptionPane.showMessageDialog(null,e);
     }
     
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayGame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1;
    private javax.swing.JTextField answer2;
    private javax.swing.JTextField answer3;
    private javax.swing.JTextField answer4;
    private javax.swing.JTextField answer5;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
