/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graham.lynch.quiz.oop.project;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author graha
 */
public class QuizGUI extends javax.swing.JFrame{
    ArrayList<Quiz> questions1 = new ArrayList<Quiz>();
    String name, question;
    int score;
    /**
     * Creates new form QuizGUI
     */
    public QuizGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuizLbl = new javax.swing.JLabel();
        ViewBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QuizLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        QuizLbl.setText("Quiz");

        ViewBtn.setText("View Leaderboard");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        playBtn.setText("Play Quiz");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(playBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(ViewBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(QuizLbl)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(QuizLbl)
                .addGap(74, 74, 74)
                .addComponent(playBtn)
                .addGap(66, 66, 66)
                .addComponent(ViewBtn)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        /*String name;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("Quiz.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            while (name != null) {
                JOptionPane.showMessageDialog(null, "Name : " + name);
                name = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
      File inFile;
      FileInputStream fStream;
      ObjectInputStream oStream;
      
      try{
          inFile = new File("namesandscores.dat");
          fStream = new FileInputStream(inFile);
          oStream = new ObjectInputStream (fStream);
          
          Quiz1 myQuiz;
          myQuiz =(Quiz1) oStream.readObject();
          
          JOptionPane.showMessageDialog(null, "Name:" + myQuiz.getName() + "Score:" + myQuiz.getScore1());
          
          oStream.close();
      }
      catch(IOException e){
          JOptionPane.showMessageDialog(null, e);
      }
      catch(ClassNotFoundException ex){
          JOptionPane.showMessageDialog(null, ex);
      }
    }//GEN-LAST:event_ViewBtnActionPerformed
public static void main(String args[]) {
         FileIO myFileIO = new FileIO();
        //create arraylist of questions
        ArrayList<Quiz> questions1;
        //
        questions1 = myFileIO.readQuestionsFromFile();
        //
        if (questions1 == null) {
            questions1 = new ArrayList<>();

            Quiz q;

            q = new Quiz("Who is the president of the United States of America?");
            questions1.add(q);
            q = new Quiz("What is the second smallest county in Ireland?");
            questions1.add(q);
            q = new Quiz("What is the County town of County Kerry?");
            questions1.add(q);
            q = new Quiz("The Book of Kells was written in what language?");
            questions1.add(q);
            q = new Quiz("In what year was the Battle of Clontarf?");
            questions1.add(q);
            q = new Quiz("What was the first country to win the World Cup twice?");
            questions1.add(q);
            q = new Quiz("What does NCI stand for?");
            questions1.add(q);
            q = new Quiz("Which early President of the United States, as well as writing most of the Declaration of Independence, also invented the swivel chair?");
            questions1.add(q);
            q = new Quiz("What stadium to Arsenal Football club play in?");
            questions1.add(q);
            q = new Quiz("What is the capital of England?");
            questions1.add(q);

            myFileIO.writeQuestionsToFile(questions1);
        }
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }
    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
      PlayGame myPlayGame = new PlayGame(name);
      myPlayGame.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_playBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuizLbl;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton playBtn;
    // End of variables declaration//GEN-END:variables
}
